### ISSUE TITLE
FieldOfView tile_shape has ambiguous (x, y) ordering

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/sptx-format#23]
The schema claims that it is ordered (x, y) 
https://github.com/spacetx/sptx-format/blob/master/schema/field_of_view/field_of_view.json#L91

Internally, we don't validate on this field yet, we simply slurp in the data and make sure that the sizes fit. However, we might want to provide information on a TileSet (before it's loaded into memory). 

We should replace this with an explicit map of `{x: size, y: size}`, instead of a list to prevent errors.

**Comment by ttung** [comment]
Hm... interesting that it's (x, y).  I thought in the code it's all (y, x).

**Comment by ambrosejcarr** [comment]
Ported to spacetx/starfish
