### ISSUE TITLE
Investigate using linked schema 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/sptx-format#6]
@hewgreen suggested that HCA metadata has outlawed the type of implicit linking we have in our specification. 

Example experiment.json
```
{
  hybridization_images: "hybridization.json",
  ..., 
}
```
In existing specification, we link a _file_ which is implicitly of a particular type. Here it can be either an `fov_manifest.json` or a `field_of_view.json`. 

HCA metadata suggests making it an explicit link, wherein it should contain the metadata structure. Investigate the pros/cons of this for our use cases.

**Comment by hewgreen** [comment]
In the HCA we only have implicit linking in file type schemas which are our most granular type of schemas. There we would have an attribute that would say filename = 'hca_001.fastq.gz'. Within the metadata schema graph all links are explicit links to objects using $ref. As spacetx uses JSON everywhere I'd probably recommend limiting implicit linking to JSON 'data files' that are not part of the schema and stick to $ref linking within the metadata schema.

**Comment by joshmoore** [comment]
for my own reference: https://swagger.io/docs/specification/using-ref/

**Comment by ambrosejcarr** [comment]
@hewgreen if we wanted to link the schemas with $ref, is that compatible with storing a _separate_ file on the file system the way we do now? 

e.g. we have: 
```
experiment.json
hybridization-manifest.json
nuclei-manifest.json
hyb-fov-001.json
...
hyb-fov-00N.json
```
And don't want to have to pile all those into a single json file. As far as I can tell, `$ref` allows us to link up schema objects, but then it will expect a single file on the other end, which would be a significant change for the format.

**Comment by ambrosejcarr** [comment]
We decided on linking with file IDs for better UX .
